version: '2'
services:
    esmeurexreferential-app:
        image: esmeurexreferential
        external_links:
            - esmeurexreferential-mongodb:mongodb
            - jhipster-registry:registry
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://registry:8761/eureka/
            - SPRING_CLOUD_CONFIG_URI=http://registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=esmeurexreferential
    esmeurexreferential-mongodb:
        extends:
            file: mongodb.yml
            service: esmeurexreferential-mongodb
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
